name: C/C++ CI

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: CXX=g++-10 make
    - name: make test
      run: CXX=g++-10 make test
