name: C/C++ CI

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: gather
      run: git submodule update --init --recursive
    - name: make
      run: CXX=g++-10 make
    - name: make test
      run: CXX=g++-10 make test
